
[[override]]
  name = "github.com/op/go-logging"
  revision = "970db520ece77730c7e4724c61121037378659d9"

[[override]]
  name = "github.com/google/martian"
  revision = "140c935a5d0d15e2cdc24b1f58668f410497fc3c"

[[override]]
  version = "=1.1.1"
  name = "github.com/ugorji/go"

[[override]]
  name = "go.opencensus.io"
  version = "0.21.0"

[[override]]
  name = "contrib.go.opencensus.io/exporter/ocagent"
  version = "v0.4.2"

[[override]]
  name = "github.com/coreos/etcd"
  version = "3.3.12"

[[override]]
  branch = "master"
  name = "github.com/devopsfaith/krakend"

[[override]]
  version = "0.8.0"
  name = "github.com/devopsfaith/krakend-metrics"

[[constraint]]
  name = "github.com/go-contrib/uuid"
  version = "v1.2.0"

[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "1.2.0"

[[constraint]]
  version = "0.9.0"
  name = "github.com/devopsfaith/krakend-cel"

[[constraint]]
  branch = "master"
  name = "github.com/devopsfaith/krakend-flexibleconfig"

[[constraint]]
  version = "0.5.0"
  name = "github.com/devopsfaith/krakend-xml"

[[constraint]]
  version = "0.5.0"
  name = "github.com/devopsfaith/krakend-rss"

[[constraint]]
  branch = "master"
  name = "github.com/letgoapp/krakend-influx"

[[constraint]]
  version = "0.5"
  name = "github.com/devopsfaith/krakend"

[[constraint]]
  branch = "master"
  name = "github.com/devopsfaith/krakend-circuitbreaker"

[[constraint]]
  version = "0.9.0"
  name = "github.com/devopsfaith/krakend-cobra"

[[constraint]]
  branch = "master"
  name = "github.com/devopsfaith/krakend-pubsub"

[[constraint]]
  branch = "master"
  name = "github.com/devopsfaith/krakend-etcd"

[[constraint]]
  branch = "master"
  name = "github.com/devopsfaith/krakend-gologging"

[[constraint]]
  version = "0.6.0"
  name = "github.com/devopsfaith/krakend-httpsecure"

[[constraint]]
  branch = "master"
  name = "github.com/devopsfaith/krakend-httpcache"

[[constraint]]
  branch = "master"
  name = "github.com/devopsfaith/krakend-amqp"

[[constraint]]
  branch = "master"
  name = "github.com/devopsfaith/krakend-martian"

[[constraint]]
  version = "0.8.0"
  name = "github.com/devopsfaith/krakend-metrics"

[[constraint]]
  version = "0.8.0"
  name = "github.com/devopsfaith/krakend-oauth2-clientcredentials"

[[constraint]]
  version = "0.9.0"
  name = "github.com/devopsfaith/krakend-ratelimit"

[[constraint]]
  branch = "master"
  name = "github.com/devopsfaith/krakend-viper"

[[constraint]]
  branch = "master"
  name = "github.com/devopsfaith/krakend-opencensus"

[[constraint]]
  version = "0.8.1"
  name = "github.com/devopsfaith/krakend-jose"

[[constraint]]
  branch = "master"
  name = "github.com/devopsfaith/krakend-jsonschema"

[[constraint]]
  version = "0.7.0"
  name = "github.com/devopsfaith/bloomfilter"

[[constraint]]
  branch = "master"
  name = "github.com/devopsfaith/krakend-consul"

[[constraint]]
  version = "0.6.0"
  name = "github.com/devopsfaith/krakend-cors"

[[constraint]]
  branch = "master"
  name = "github.com/devopsfaith/krakend-usage"

[[constraint]]
  branch = "master"
  name = "github.com/devopsfaith/krakend-gelf"

[[constraint]]
  branch = "master"
  name = "github.com/devopsfaith/krakend-logstash"
